version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      name: nt-qdrant
      args:
        - FEATURES=qdrant
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - STORAGE=qdrant
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./data:/app/data
    networks:
      - nt-network

  qdrant:
    image: docker.io/qdrant/qdrant:latest
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - nt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:

networks:
  nt-network:
    driver: bridge 