version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      name: nt-chroma
      args:
        - FEATURES=chroma
    depends_on:
      chroma:
        condition: service_healthy
    environment:
      - STORAGE=chroma
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./data:/app/data
    networks:
      - nt-network

  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8000:8000"  # REST API
    expose:
      - 8000
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - nt-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:

networks:
  nt-network:
    driver: bridge 