version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FEATURES=chroma
    depends_on:
      chroma:
        condition: service_healthy
    environment:
      - RUST_LOG=info
    volumes:
      - .:/app

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"  # REST API
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data: 