version: '3.8'

services:
  app_chroma:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FEATURES=chroma,ollama
    depends_on:
      chroma:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - RUST_LOG=info
      - STORAGE=chroma
      - MODEL_URL=http://ollama:11434
      - BACKEND_URL=http://chroma:8000
    volumes:
      - ./data:/app/data
    networks:
      - nt-network

  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8000:8000"  # REST API
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_LOG_LEVEL=debug
      - CHROMA_DEBUG=true
    networks:
      - nt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    expose:
      - 11434
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    command: ["sh", "-c", "ollama serve & sleep 10 && ollama pull 8b-wraith/deepseek-v3-0324 && tail -f /dev/null"]
    networks:
      - nt-network

volumes:
  chroma_data:
  ollama_data:

networks:
  nt-network:
    driver: bridge 